queue_rules:
  - name: default
    conditions:
      - "check-success=build"

pull_request_rules:
  - name: merge_dependabot
    conditions:
      - "author=dependabot[bot]"
      - "check-success=build"
    actions:
      queue:
        name: default
        update_method: rebase

  - name: delete_merged
    conditions:
      - merged
    actions:
      delete_head_branch: { }
