queue_rules:
  - name: default
    queue_conditions:
      - "author=renovate[bot]"
      - "check-success=build"
    merge_conditions:
      - "check-success=build"
    update_method: rebase

pull_request_rules:
  - name: delete_merged
    conditions:
      - merged
    actions:
      delete_head_branch: {}
