language: java

jdk: openjdk11

addons:
  sonarcloud:
    organization: beatngu13-github
    token: "${SC_TOKEN}"

cache:
  directories:
    - "${HOME}/.m2/"
    - "${HOME}/.sonar/cache/"

install: true

script: mvn clean verify sonar:sonar -Pcoverage
